apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80
        volumeMounts:
          - name: applogs
            mountPath: /var/log/nginx
      - name: logshipper
        image: k8s-logship-sidecar:v1.0.0
        env:
          - name: LOG_DIRECTORY
            value: /logs
          - name: LOG_FILE_PATTERN
            value: .+.log
          - name: LOG_SCAN_INTERVAL
            value: "10"
        volumeMounts:
        - name: applogs
          mountPath: /logs
          readOnly: true
      volumes:
        - name: applogs
          emptyDir: {}